/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EngagementBenefitEnrollmentsInnerPlan
 */
public class EngagementBenefitEnrollmentsInnerPlanTest {
    private final EngagementBenefitEnrollmentsInnerPlan model = new EngagementBenefitEnrollmentsInnerPlan();

    /**
     * Model tests for EngagementBenefitEnrollmentsInnerPlan
     */
    @Test
    public void testEngagementBenefitEnrollmentsInnerPlan() {
        // TODO: test EngagementBenefitEnrollmentsInnerPlan
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'descriptiveName'
     */
    @Test
    public void descriptiveNameTest() {
        // TODO: test descriptiveName
    }

}
