/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EngagementBenefitEnrollmentsInnerPlan;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EngagementBenefitEnrollmentsInner
 */
public class EngagementBenefitEnrollmentsInnerTest {
    private final EngagementBenefitEnrollmentsInner model = new EngagementBenefitEnrollmentsInner();

    /**
     * Model tests for EngagementBenefitEnrollmentsInner
     */
    @Test
    public void testEngagementBenefitEnrollmentsInner() {
        // TODO: test EngagementBenefitEnrollmentsInner
    }

    /**
     * Test the property 'benefitEnrollmentId'
     */
    @Test
    public void benefitEnrollmentIdTest() {
        // TODO: test benefitEnrollmentId
    }

    /**
     * Test the property 'plan'
     */
    @Test
    public void planTest() {
        // TODO: test plan
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

}
