/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PhoneNumber;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EngagementPersonalDetailsPhoneNumbers
 */
public class EngagementPersonalDetailsPhoneNumbersTest {
    private final EngagementPersonalDetailsPhoneNumbers model = new EngagementPersonalDetailsPhoneNumbers();

    /**
     * Model tests for EngagementPersonalDetailsPhoneNumbers
     */
    @Test
    public void testEngagementPersonalDetailsPhoneNumbers() {
        // TODO: test EngagementPersonalDetailsPhoneNumbers
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

    /**
     * Test the property 'emergency'
     */
    @Test
    public void emergencyTest() {
        // TODO: test emergency
    }

}
