/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EngagementBenefitEnrollmentsInner;
import com.konfigthis.client.model.EngagementDepartment;
import com.konfigthis.client.model.EngagementPersonalDetails;
import com.konfigthis.client.model.EngagementTerminationsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Engagement
 */
public class EngagementTest {
    private final Engagement model = new Engagement();

    /**
     * Model tests for Engagement
     */
    @Test
    public void testEngagement() {
        // TODO: test Engagement
    }

    /**
     * Test the property 'engagementId'
     */
    @Test
    public void engagementIdTest() {
        // TODO: test engagementId
    }

    /**
     * Test the property 'modifiedAt'
     */
    @Test
    public void modifiedAtTest() {
        // TODO: test modifiedAt
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'engagementType'
     */
    @Test
    public void engagementTypeTest() {
        // TODO: test engagementType
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'personalDetails'
     */
    @Test
    public void personalDetailsTest() {
        // TODO: test personalDetails
    }

    /**
     * Test the property 'employment'
     */
    @Test
    public void employmentTest() {
        // TODO: test employment
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'benefitEnrollments'
     */
    @Test
    public void benefitEnrollmentsTest() {
        // TODO: test benefitEnrollments
    }

    /**
     * Test the property 'terminations'
     */
    @Test
    public void terminationsTest() {
        // TODO: test terminations
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

}
