/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Amount;
import com.konfigthis.client.model.ExpenseEngagement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Expense
 */
public class ExpenseTest {
    private final Expense model = new Expense();

    /**
     * Model tests for Expense
     */
    @Test
    public void testExpense() {
        // TODO: test Expense
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'expenseId'
     */
    @Test
    public void expenseIdTest() {
        // TODO: test expenseId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'incurredOn'
     */
    @Test
    public void incurredOnTest() {
        // TODO: test incurredOn
    }

    /**
     * Test the property 'submittedAt'
     */
    @Test
    public void submittedAtTest() {
        // TODO: test submittedAt
    }

    /**
     * Test the property 'reviewState'
     */
    @Test
    public void reviewStateTest() {
        // TODO: test reviewState
    }

    /**
     * Test the property 'reviewedAt'
     */
    @Test
    public void reviewedAtTest() {
        // TODO: test reviewedAt
    }

    /**
     * Test the property 'receiptAmount'
     */
    @Test
    public void receiptAmountTest() {
        // TODO: test receiptAmount
    }

    /**
     * Test the property 'receiptUrl'
     */
    @Test
    public void receiptUrlTest() {
        // TODO: test receiptUrl
    }

    /**
     * Test the property 'engagement'
     */
    @Test
    public void engagementTest() {
        // TODO: test engagement
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

}
