/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpensesCreateOperationKeyRequestReceiptAmount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpensesCreateOperationKeyRequest
 */
public class ExpensesCreateOperationKeyRequestTest {
    private final ExpensesCreateOperationKeyRequest model = new ExpensesCreateOperationKeyRequest();

    /**
     * Model tests for ExpensesCreateOperationKeyRequest
     */
    @Test
    public void testExpensesCreateOperationKeyRequest() {
        // TODO: test ExpensesCreateOperationKeyRequest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'engagementId'
     */
    @Test
    public void engagementIdTest() {
        // TODO: test engagementId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'incurredOn'
     */
    @Test
    public void incurredOnTest() {
        // TODO: test incurredOn
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'receiptUrl'
     */
    @Test
    public void receiptUrlTest() {
        // TODO: test receiptUrl
    }

    /**
     * Test the property 'receiptAmount'
     */
    @Test
    public void receiptAmountTest() {
        // TODO: test receiptAmount
    }

}
