/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Meta
 */
public class MetaTest {
    private final Meta model = new Meta();

    /**
     * Model tests for Meta
     */
    @Test
    public void testMeta() {
        // TODO: test Meta
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'firstUrl'
     */
    @Test
    public void firstUrlTest() {
        // TODO: test firstUrl
    }

    /**
     * Test the property 'lastUrl'
     */
    @Test
    public void lastUrlTest() {
        // TODO: test lastUrl
    }

    /**
     * Test the property 'pageUrl'
     */
    @Test
    public void pageUrlTest() {
        // TODO: test pageUrl
    }

    /**
     * Test the property 'nextUrl'
     */
    @Test
    public void nextUrlTest() {
        // TODO: test nextUrl
    }

    /**
     * Test the property 'prevUrl'
     */
    @Test
    public void prevUrlTest() {
        // TODO: test prevUrl
    }

}
