/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PayrollRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Payroll
 */
public class PayrollTest {
    private final Payroll model = new Payroll();

    /**
     * Model tests for Payroll
     */
    @Test
    public void testPayroll() {
        // TODO: test Payroll
    }

    /**
     * Test the property 'payrollId'
     */
    @Test
    public void payrollIdTest() {
        // TODO: test payrollId
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'cutoffTimeForPayroll'
     */
    @Test
    public void cutoffTimeForPayrollTest() {
        // TODO: test cutoffTimeForPayroll
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'payrollRecordsCount'
     */
    @Test
    public void payrollRecordsCountTest() {
        // TODO: test payrollRecordsCount
    }

    /**
     * Test the property 'records'
     */
    @Test
    public void recordsTest() {
        // TODO: test records
    }

}
