/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Amount;
import com.konfigthis.client.model.PayrollRecordEngagement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayrollRecord
 */
public class PayrollRecordTest {
    private final PayrollRecord model = new PayrollRecord();

    /**
     * Model tests for PayrollRecord
     */
    @Test
    public void testPayrollRecord() {
        // TODO: test PayrollRecord
    }

    /**
     * Test the property 'engagementId'
     */
    @Test
    public void engagementIdTest() {
        // TODO: test engagementId
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'monthlyPaymentsTotalAmount'
     */
    @Test
    public void monthlyPaymentsTotalAmountTest() {
        // TODO: test monthlyPaymentsTotalAmount
    }

    /**
     * Test the property 'allowancesTotalAmount'
     */
    @Test
    public void allowancesTotalAmountTest() {
        // TODO: test allowancesTotalAmount
    }

    /**
     * Test the property 'benefitsTotalAmount'
     */
    @Test
    public void benefitsTotalAmountTest() {
        // TODO: test benefitsTotalAmount
    }

    /**
     * Test the property 'bonusesTotalAmount'
     */
    @Test
    public void bonusesTotalAmountTest() {
        // TODO: test bonusesTotalAmount
    }

    /**
     * Test the property 'addOnsTotalAmount'
     */
    @Test
    public void addOnsTotalAmountTest() {
        // TODO: test addOnsTotalAmount
    }

    /**
     * Test the property 'taxesTotalAmount'
     */
    @Test
    public void taxesTotalAmountTest() {
        // TODO: test taxesTotalAmount
    }

    /**
     * Test the property 'trueUpsTotalAmount'
     */
    @Test
    public void trueUpsTotalAmountTest() {
        // TODO: test trueUpsTotalAmount
    }

    /**
     * Test the property 'oysterFeesTotalAmount'
     */
    @Test
    public void oysterFeesTotalAmountTest() {
        // TODO: test oysterFeesTotalAmount
    }

    /**
     * Test the property 'engagement'
     */
    @Test
    public void engagementTest() {
        // TODO: test engagement
    }

}
