/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TimeOffEngagementDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TimeOffRequest
 */
public class TimeOffRequestTest {
    private final TimeOffRequest model = new TimeOffRequest();

    /**
     * Model tests for TimeOffRequest
     */
    @Test
    public void testTimeOffRequest() {
        // TODO: test TimeOffRequest
    }

    /**
     * Test the property 'timeOffRequestId'
     */
    @Test
    public void timeOffRequestIdTest() {
        // TODO: test timeOffRequestId
    }

    /**
     * Test the property 'engagement'
     */
    @Test
    public void engagementTest() {
        // TODO: test engagement
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'firstDayDuration'
     */
    @Test
    public void firstDayDurationTest() {
        // TODO: test firstDayDuration
    }

    /**
     * Test the property 'lastDayDuration'
     */
    @Test
    public void lastDayDurationTest() {
        // TODO: test lastDayDuration
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'requesterComments'
     */
    @Test
    public void requesterCommentsTest() {
        // TODO: test requesterComments
    }

    /**
     * Test the property 'rejectionReason'
     */
    @Test
    public void rejectionReasonTest() {
        // TODO: test rejectionReason
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'periodInHours'
     */
    @Test
    public void periodInHoursTest() {
        // TODO: test periodInHours
    }

}
