/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TimeOffEngagementDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TimeOffEntitlementsInner
 */
public class TimeOffEntitlementsInnerTest {
    private final TimeOffEntitlementsInner model = new TimeOffEntitlementsInner();

    /**
     * Model tests for TimeOffEntitlementsInner
     */
    @Test
    public void testTimeOffEntitlementsInner() {
        // TODO: test TimeOffEntitlementsInner
    }

    /**
     * Test the property 'engagement'
     */
    @Test
    public void engagementTest() {
        // TODO: test engagement
    }

    /**
     * Test the property 'annualEntitlement'
     */
    @Test
    public void annualEntitlementTest() {
        // TODO: test annualEntitlement
    }

    /**
     * Test the property 'accrued'
     */
    @Test
    public void accruedTest() {
        // TODO: test accrued
    }

    /**
     * Test the property 'carried'
     */
    @Test
    public void carriedTest() {
        // TODO: test carried
    }

    /**
     * Test the property 'adjustedAdhoc'
     */
    @Test
    public void adjustedAdhocTest() {
        // TODO: test adjustedAdhoc
    }

    /**
     * Test the property 'taken'
     */
    @Test
    public void takenTest() {
        // TODO: test taken
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'upcoming'
     */
    @Test
    public void upcomingTest() {
        // TODO: test upcoming
    }

    /**
     * Test the property 'projectedBalance'
     */
    @Test
    public void projectedBalanceTest() {
        // TODO: test projectedBalance
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

}
