/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpensesCreateOperationKeyRequestReceiptAmount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ExpensesCreateOperationKeyRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpensesCreateOperationKeyRequest {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ENGAGEMENT_ID = "engagementId";
  @SerializedName(SERIALIZED_NAME_ENGAGEMENT_ID)
  private String engagementId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_INCURRED_ON = "incurredOn";
  @SerializedName(SERIALIZED_NAME_INCURRED_ON)
  private LocalDate incurredOn;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;

  public static final String SERIALIZED_NAME_RECEIPT_URL = "receiptUrl";
  @SerializedName(SERIALIZED_NAME_RECEIPT_URL)
  private String receiptUrl;

  public static final String SERIALIZED_NAME_RECEIPT_AMOUNT = "receiptAmount";
  @SerializedName(SERIALIZED_NAME_RECEIPT_AMOUNT)
  private ExpensesCreateOperationKeyRequestReceiptAmount receiptAmount;

  public ExpensesCreateOperationKeyRequest() {
  }

  public ExpensesCreateOperationKeyRequest description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public ExpensesCreateOperationKeyRequest engagementId(String engagementId) {
    
    
    if (engagementId != null && engagementId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for engagementId. Length must be greater than or equal to 1.");
    }
    
    this.engagementId = engagementId;
    return this;
  }

   /**
   * Get engagementId
   * @return engagementId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getEngagementId() {
    return engagementId;
  }


  public void setEngagementId(String engagementId) {
    
    
    if (engagementId != null && engagementId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for engagementId. Length must be greater than or equal to 1.");
    }
    this.engagementId = engagementId;
  }


  public ExpensesCreateOperationKeyRequest name(String name) {
    
    
    if (name != null && name.length() < 1) {
      throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 1.");
    }
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    if (name != null && name.length() < 1) {
      throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 1.");
    }
    this.name = name;
  }


  public ExpensesCreateOperationKeyRequest incurredOn(LocalDate incurredOn) {
    
    
    if (incurredOn != null && incurredOn.length() < 1) {
      throw new IllegalArgumentException("Invalid value for incurredOn. Length must be greater than or equal to 1.");
    }
    
    this.incurredOn = incurredOn;
    return this;
  }

   /**
   * Get incurredOn
   * @return incurredOn
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public LocalDate getIncurredOn() {
    return incurredOn;
  }


  public void setIncurredOn(LocalDate incurredOn) {
    
    
    if (incurredOn != null && incurredOn.length() < 1) {
      throw new IllegalArgumentException("Invalid value for incurredOn. Length must be greater than or equal to 1.");
    }
    this.incurredOn = incurredOn;
  }


  public ExpensesCreateOperationKeyRequest category(String category) {
    
    
    if (category != null && category.length() < 1) {
      throw new IllegalArgumentException("Invalid value for category. Length must be greater than or equal to 1.");
    }
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getCategory() {
    return category;
  }


  public void setCategory(String category) {
    
    
    if (category != null && category.length() < 1) {
      throw new IllegalArgumentException("Invalid value for category. Length must be greater than or equal to 1.");
    }
    this.category = category;
  }


  public ExpensesCreateOperationKeyRequest receiptUrl(String receiptUrl) {
    
    
    if (receiptUrl != null && receiptUrl.length() < 1) {
      throw new IllegalArgumentException("Invalid value for receiptUrl. Length must be greater than or equal to 1.");
    }
    
    this.receiptUrl = receiptUrl;
    return this;
  }

   /**
   * Get receiptUrl
   * @return receiptUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getReceiptUrl() {
    return receiptUrl;
  }


  public void setReceiptUrl(String receiptUrl) {
    
    
    if (receiptUrl != null && receiptUrl.length() < 1) {
      throw new IllegalArgumentException("Invalid value for receiptUrl. Length must be greater than or equal to 1.");
    }
    this.receiptUrl = receiptUrl;
  }


  public ExpensesCreateOperationKeyRequest receiptAmount(ExpensesCreateOperationKeyRequestReceiptAmount receiptAmount) {
    
    
    
    
    this.receiptAmount = receiptAmount;
    return this;
  }

   /**
   * Get receiptAmount
   * @return receiptAmount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ExpensesCreateOperationKeyRequestReceiptAmount getReceiptAmount() {
    return receiptAmount;
  }


  public void setReceiptAmount(ExpensesCreateOperationKeyRequestReceiptAmount receiptAmount) {
    
    
    
    this.receiptAmount = receiptAmount;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpensesCreateOperationKeyRequest instance itself
   */
  public ExpensesCreateOperationKeyRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpensesCreateOperationKeyRequest expensesCreateOperationKeyRequest = (ExpensesCreateOperationKeyRequest) o;
    return Objects.equals(this.description, expensesCreateOperationKeyRequest.description) &&
        Objects.equals(this.engagementId, expensesCreateOperationKeyRequest.engagementId) &&
        Objects.equals(this.name, expensesCreateOperationKeyRequest.name) &&
        Objects.equals(this.incurredOn, expensesCreateOperationKeyRequest.incurredOn) &&
        Objects.equals(this.category, expensesCreateOperationKeyRequest.category) &&
        Objects.equals(this.receiptUrl, expensesCreateOperationKeyRequest.receiptUrl) &&
        Objects.equals(this.receiptAmount, expensesCreateOperationKeyRequest.receiptAmount)&&
        Objects.equals(this.additionalProperties, expensesCreateOperationKeyRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, engagementId, name, incurredOn, category, receiptUrl, receiptAmount, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpensesCreateOperationKeyRequest {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    engagementId: ").append(toIndentedString(engagementId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    incurredOn: ").append(toIndentedString(incurredOn)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    receiptUrl: ").append(toIndentedString(receiptUrl)).append("\n");
    sb.append("    receiptAmount: ").append(toIndentedString(receiptAmount)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("engagementId");
    openapiFields.add("name");
    openapiFields.add("incurredOn");
    openapiFields.add("category");
    openapiFields.add("receiptUrl");
    openapiFields.add("receiptAmount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("engagementId");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("incurredOn");
    openapiRequiredFields.add("category");
    openapiRequiredFields.add("receiptUrl");
    openapiRequiredFields.add("receiptAmount");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpensesCreateOperationKeyRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpensesCreateOperationKeyRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpensesCreateOperationKeyRequest is not found in the empty JSON string", ExpensesCreateOperationKeyRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExpensesCreateOperationKeyRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("engagementId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `engagementId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("engagementId").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      if (!jsonObj.get("receiptUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receiptUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receiptUrl").toString()));
      }
      // validate the required field `receiptAmount`
      ExpensesCreateOperationKeyRequestReceiptAmount.validateJsonObject(jsonObj.getAsJsonObject("receiptAmount"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpensesCreateOperationKeyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpensesCreateOperationKeyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpensesCreateOperationKeyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpensesCreateOperationKeyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpensesCreateOperationKeyRequest>() {
           @Override
           public void write(JsonWriter out, ExpensesCreateOperationKeyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpensesCreateOperationKeyRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpensesCreateOperationKeyRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpensesCreateOperationKeyRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpensesCreateOperationKeyRequest
  * @throws IOException if the JSON string is invalid with respect to ExpensesCreateOperationKeyRequest
  */
  public static ExpensesCreateOperationKeyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpensesCreateOperationKeyRequest.class);
  }

 /**
  * Convert an instance of ExpensesCreateOperationKeyRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

