/*
 * Endpoints
 * Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.PayrollGetAllPayrollsResponse;
import com.konfigthis.client.model.PayrollGetByIdResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PayrollApi
 */
@Disabled
public class PayrollApiTest {

    private static PayrollApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PayrollApi(apiClient);
    }

    /**
     * Retrieve all payroll
     *
     * Returns a list of payrolls
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllPayrollsTest() throws ApiException {
        Integer perPage = null;
        Integer page = null;
        String from = null;
        String to = null;
        Boolean includeRecords = null;
        PayrollGetAllPayrollsResponse response = api.getAllPayrolls()
                .perPage(perPage)
                .page(page)
                .from(from)
                .to(to)
                .includeRecords(includeRecords)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve an individual payroll
     *
     * Returns details for a payroll with a given payroll ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String id = null;
        PayrollGetByIdResponse response = api.getById(id)
                .execute();
        // TODO: test validations
    }

}
